title: small things
description: Black Cat + Art of Small Things
url: "https://2pix.github.io"
baseurl: "/small-things"

theme: null

markdown: kramdown
permalink: /:categories/:year-:month-:day-:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sections:
  - key: black-cat
    label: Black Cat
  - key: the-floor
    label: The Floor
  - key: the-art-of-small-things
    label: The Art of

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .bundle
